//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.ContenType.DeploymentHub.DomainServices.Loggers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Summary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Summary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.ContenType.DeploymentHub.DomainServices.Loggers.Resources.Summary", typeof(Summary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///Hello {0}
        ///&lt;/div&gt; 
        ///&lt;br/&gt;
        ///Your promote action on hub:{1} has &lt;b&gt;successfully&lt;/b&gt; completed.
        ///
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Overview request&lt;/h2&gt;
        ///
        ///&lt;p&gt;Your requested promote action involved: 
        ///&lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;{2} Site columns&lt;/li&gt;
        ///&lt;li&gt;{3} Content types&lt;/li&gt;
        ///&lt;li&gt;{4} Target sites&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Overview actions&lt;/h2&gt;
        ///&lt;p&gt;After the pre-checks a total of {5} actions where performed: 
        ///&lt;ul&gt;
        ///&lt;li&gt;SiteColumn actions:{6}
        ///	&lt;ul&gt;
        ///	{7}
        ///	&lt;/ul&gt;
        ///&lt;/li&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PromoteExecutedMail {
            get {
                return ResourceManager.GetString("PromoteExecutedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///Hello {0}
        ///&lt;/div&gt; 
        ///&lt;br/&gt;
        ///&lt;br/&gt;
        ///Your requested promote on &lt;b&gt;{1}&lt;/b&gt; has &lt;b&gt;failed&lt;/b&gt;
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Overview actions&lt;/h2&gt;
        ///
        ///&lt;p&gt;Failed because: {2}
        ///&lt;/p&gt;
        ///
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Reference&lt;/h2&gt;
        ///
        ///&lt;ul&gt;
        ///&lt;li&gt;ID given to this request:{3}&lt;/li&gt;
        ///&lt;li&gt;List item id in the status list: {4}&lt;/li&gt;
        ///&lt;li&gt;Full error message: {5}&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///        &lt;div&gt;
        ///        Yours truly, &lt;br/&gt;
        ///        The SharePoint Support Team
        ///        &lt;/div&gt;.
        /// </summary>
        internal static string PromoteFailedMail {
            get {
                return ResourceManager.GetString("PromoteFailedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///Hello {0}
        ///&lt;/div&gt; 
        ///&lt;br/&gt;
        ///Your publish action on hub:{1} has &lt;b&gt;successfully&lt;/b&gt; completed.
        ///
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Overview request&lt;/h2&gt;
        ///
        ///&lt;p&gt;Your requested publish action involved: 
        ///&lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;{2} Site columns&lt;/li&gt;
        ///&lt;li&gt;{3} Content types&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Overview actions&lt;/h2&gt;
        ///&lt;p&gt;After the pre-checks a total of {4} actions where performed: 
        ///&lt;ul&gt;
        ///&lt;li&gt;SiteColumn actions:{5}
        ///	&lt;ul&gt;
        ///	{6}
        ///	&lt;/ul&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt;ContentType actions:{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublishExecutedMail {
            get {
                return ResourceManager.GetString("PublishExecutedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///Hello {0}
        ///&lt;/div&gt; 
        ///&lt;br/&gt;
        ///&lt;br/&gt;
        ///Your requested publish on &lt;b&gt;{1}&lt;/b&gt; has &lt;b&gt;failed&lt;/b&gt;
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Overview actions&lt;/h2&gt;
        ///
        ///&lt;p&gt;Failed because: {2}
        ///&lt;/p&gt;
        ///
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Reference&lt;/h2&gt;
        ///
        ///&lt;ul&gt;
        ///&lt;li&gt;ID given to this request:{3}&lt;/li&gt;
        ///&lt;li&gt;List item id in the status list: {4}&lt;/li&gt;
        ///&lt;li&gt;Full error message: {5}&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///        &lt;div&gt;
        ///        Yours truly, &lt;br/&gt;
        ///        The SharePoint Support Team
        ///        &lt;/div&gt;.
        /// </summary>
        internal static string PublishFailedMail {
            get {
                return ResourceManager.GetString("PublishFailedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///Hello {0}
        ///&lt;/div&gt; 
        ///&lt;br/&gt;
        ///Your push action on hub:{1} has &lt;b&gt;successfully&lt;/b&gt; completed.
        ///
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Overview request&lt;/h2&gt;
        ///
        ///&lt;p&gt;Your requested push action involved: 
        ///&lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;{2} Site columns&lt;/li&gt;
        ///&lt;li&gt;{3} Content types&lt;/li&gt;
        ///&lt;li&gt;{4} Target sites&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Overview actions&lt;/h2&gt;
        ///&lt;p&gt;After the pre-checks a total of {5} actions where performed: 
        ///&lt;ul&gt;
        ///&lt;li&gt;SiteColumn actions:{6}
        ///	&lt;ul&gt;
        ///	{7}
        ///	&lt;/ul&gt;
        ///&lt;/li&gt;
        ///&lt;li&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PushExecutedMail {
            get {
                return ResourceManager.GetString("PushExecutedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///Hello {0}
        ///&lt;/div&gt; 
        ///&lt;br/&gt;
        ///&lt;br/&gt;
        ///Your requested push on &lt;b&gt;{1}&lt;/b&gt; has &lt;b&gt;failed&lt;/b&gt;
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Overview actions&lt;/h2&gt;
        ///
        ///&lt;p&gt;Failed because: {2}
        ///&lt;/p&gt;
        ///
        ///&lt;h2 style=&quot;text-decoration: underline;&quot;&gt;Reference&lt;/h2&gt;
        ///
        ///&lt;ul&gt;
        ///&lt;li&gt;ID given to this request:{3}&lt;/li&gt;
        ///&lt;li&gt;List item id in the status list: {4}&lt;/li&gt;
        ///&lt;li&gt;Full error message: {5}&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///        &lt;div&gt;
        ///        Yours truly, &lt;br/&gt;
        ///        The SharePoint Support Team
        ///        &lt;/div&gt;.
        /// </summary>
        internal static string PushFailedMail {
            get {
                return ResourceManager.GetString("PushFailedMail", resourceCulture);
            }
        }
    }
}
